image: Visual Studio 2019
version: '4.2.13.1.{build}'
platform: x64
branches:
    only:
        - master
        - devel
        - develop

configuration: 
    - Release 

environment:
    PYTHON: "C:\\Python312-x64"
    matrix:
        - JC_SKSE: "64"

matrix:
    exclude:
        - configuration: Release
          JC_SKSE: "64"

install:
    - cmd: set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
    - git submodule update --init --recursive

before_build:
    - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"

build:
    project: CMakeLists.txt

after_build:
    - cmd: python tools\\install.py x64\\%CONFIGURATION% %JC_SKSE%

test_script:
    - cmd: python tools\\test.py x64\\%CONFIGURATION%\\Data\\SKSE\\Plugins\\JContainers%JC_SKSE%.dll

artifacts:
    - path: dist\*
      name: jcdistro
